server:
  port: 8088

spring:
  application:
    name: auth-service

  # R2DBC: Used by your Repositories/Services
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:15436/auth_postgres_db
    username: auth_user
    password: auth_password

  sql:
    init:
      mode: always

  # LIQUIBASE: Used during startup for migrations
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml
#    url: jdbc:postgresql://localhost:15436/auth_postgres_db
#    user: auth_user
#    password: auth_password
#    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  grpc:
    client:
      channels:
        patient-service:
          address: 'static://localhost:9001' # Matches patient-service's port
          plaintext: true

        workforce-service:
          address: 'static://localhost:9003' # Matches workforce-service's port
          plaintext: true

  kafka:
    bootstrap-servers: localhost:9094
    producer:
      # This tells Spring to turn your Objects/Maps into JSON strings automatically
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG

jwt:
  private-key-path: classpath:certs/jwt.key
  public-key-path: classpath:certs/jwt.key.pub
  issuer: "healthcore-auth-service"
  audience: "healthcore-api"