spring:
  application:
    name: auth-service

jwt:
  secret: "your-very-long-and-secure-random-string-here-32-chars-min"
  access-expiration: 900000 # 15 mins in ms
  refresh-expiration: 604800000 # 7 days in ms