name: "health-management-system"

services:
  patient-db:
    image: postgres:16-alpine
    container_name: patient-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patient_postgres_db
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d patient_postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - patient_data:/var/lib/postgresql/data
    restart: unless-stopped

  tenant-db:
    image: postgres:16-alpine
    container_name: tenant-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenant_postgres_db
    ports:
      - "15433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tenant_postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - tenant_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  patient_data:
  tenant_data: